name: Gutenberg Daily

on:
  # Jalan otomatis setiap hari
  schedule:
    # 01:00 UTC = 08:00 WIB
    - cron: "0 1 * * *"

  # Bisa dijalankan manual dari GitHub UI
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      # Run crawler
      - name: Run Gutenberg crawler
        run: |
          python crawler/crawler.py

      # Commit & push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data crawler

          git commit -m "Daily Gutenberg update" || echo "No changes to commit"

          git pull --rebase
          git push